package com.winginrian.hibernate.entity;
// Generated 2019-3-19 23:02:59 by Hibernate Tools 5.2.11.Final


import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Home object for domain model class Caseresource.
 * @see com.winginrian.hibernate.entity.Caseresource
 * @author Hibernate Tools
 */
@Stateless
public class CaseresourceHome {

    private static final Log log = LogFactory.getLog(CaseresourceHome.class);

    @PersistenceContext private EntityManager entityManager;
    
    public void persist(Caseresource transientInstance) {
        log.debug("persisting Caseresource instance");
        try {
            entityManager.persist(transientInstance);
            log.debug("persist successful");
        }
        catch (RuntimeException re) {
            log.error("persist failed", re);
            throw re;
        }
    }
    
    public void remove(Caseresource persistentInstance) {
        log.debug("removing Caseresource instance");
        try {
            entityManager.remove(persistentInstance);
            log.debug("remove successful");
        }
        catch (RuntimeException re) {
            log.error("remove failed", re);
            throw re;
        }
    }
    
    public Caseresource merge(Caseresource detachedInstance) {
        log.debug("merging Caseresource instance");
        try {
            Caseresource result = entityManager.merge(detachedInstance);
            log.debug("merge successful");
            return result;
        }
        catch (RuntimeException re) {
            log.error("merge failed", re);
            throw re;
        }
    }
    
    public Caseresource findById( Integer id) {
        log.debug("getting Caseresource instance with id: " + id);
        try {
            Caseresource instance = entityManager.find(Caseresource.class, id);
            log.debug("get successful");
            return instance;
        }
        catch (RuntimeException re) {
            log.error("get failed", re);
            throw re;
        }
    }
}

